### ISSUE TITLE
거래내역을 저장

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#108]
https://github.com/opencloset/OpenCloset-Share-Web/issues/40

iamport 와의 거래내역을 저장하기 위한 테이블을 추가해야 합니다.

**Comment by aanoaa** [comment]
`payment_history`

- id
- order_id
- imp_uid(sid)
- merchant_uid(cid)
- amount
- status
  - paid
  - ready
  - cancel
  - fail
- vendor
  - iamport-html5_inicis
  - ...
- pay_method(paid_by?)
  - vbank
  - card
  - ...
- json
- create_date

**Comment by keedi** [comment]
스키마 조금 수정해보겠습니다.

**Comment by keedi** [comment]
payment_history 를 payment와 payment_log로 둘로 나누는 중입니다. payment_log쪽에 status와 json 값을 보내는 식으로 바꿉니다.

**Comment by keedi** [comment]
`sid`, `cid`는 현재 index로 걸려 있는데 각각 고유해야 하므로 유니크 아이디로 변경하는 편이 유리할 것 같습니다.

**Comment by aanoaa** [comment]
`OpenCloset-Schema-0.044` 배포하였습니다.
