### ISSUE TITLE
주문 요청/문의와 배송 요청/문의 컬럼의 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#110]
https://github.com/opencloset/OpenCloset-Share-Web/issues/50

주문에 관한 요청/문의를 기록하는 컬럼과
배송에 관한 요청/문의를 기록하는 컬럼을 기록해야 합니다.

컬럼명을

- misc(miscellaneous)
- shipping_misc

로 하면 어떨까 합니다.

cc @keedi @yongbin

**Comment by keedi** [comment]
본 이슈 및 50번 이슈 데드라인이 언제까지인지요?

**Comment by aanoaa** [comment]
정해진 데드라인은 없습니다
꼭 필요한 기능 같아서 넣으려고 합니다

**Comment by yongbin** [comment]
`order`.`msg` , `order`.`shipping_msg` 도 괜찮을거 같습니다.

**Comment by aanoaa** [comment]
order.message 가 이미 있습니다

**Comment by aanoaa** [comment]
- order.misc(TEXT)
- order.shipping_misc(TEXT)

로 추가하도록 하겠습니다.

**Comment by aanoaa** [comment]
`0.0045` 버전 배포하고 서버+테스트서버 모두에 적용하였습니다.
