### ISSUE TITLE
주문서에서 온라인 주문여부를 기록하는 컬럼을 추가

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Schema#27]
https://github.com/opencloset/opencloset/issues/524 에서 논의된 내용으로 OpenCloset::Schema에서 처리해야할 이슈이므로 이곳에 생성합니다.  꼭 별도 가지에서 작업해서 PR형태로 보내도록 합니다.

@keedi say

> @yongbin 말씀하신 것처럼 online 여부를 기록하는 컬럼 필요합니다. 진행해주세요.
> 단, 가지에서 꼭 진행 후 모든 확인 후 머지 및 배포가 이루어져야 합니다. 스키마기
> 때문에 확인없이 머지되면 장애날 수도 있으니까요.

**Comment by keedi** [comment]
다음 이슈와 연관이 있습니다.
- opencloset/opencloset/issues/552
- opencloset/monitor/issues/70

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/issues/715

**Comment by yongbin** [comment]
온라인 서비스를 위해서 필요합니다. 진행하겠습니다.

**Comment by aanoaa** [comment]
너무 늦어지고 있습니다.
진행해주세요.

**Comment by aanoaa** [comment]
컬럼만 한개 생긴다고 해결되는 문제가 아닙니다.

지난번에 배포되지 않은 온라인 서비스를 사용하는 바람에 오프라인 서비스에 문제가 생긴적이
있습니다. 현재 서비스 되고 있는 오프라인 대여에서 문제가 없도록 조건을 추가해주어야
합니다.

```
SELECT * FROM `order` WHERE online = 0;
```

이런식으로요.

**Comment by yongbin** [comment]
저는 단순하게 7시, 10시 주문을 확인하는 쿼리만 확인하려고 했는데(https://github.com/opencloset/opencloset/issues/715 ) 그게 아니라 말씀하신것 처럼 주문을 대상으로 하는 쿼리에 전체적으로 영향이 있는지를 확인해야할거 같습니다. 참고하겠습니다.

**Comment by aanoaa** [comment]
주문서에 컬럼을 하나 추가하겠습니다.

```
`online` INT DEFAULT 0 COMMENT '0 is offline, otherwise online'
```

0이면 offline 주문서이고 다른 모든 것은 online 주문서임을 나타냅니다.
