### ISSUE TITLE
포장 완료 상태 추가

### ISSUE THREAD

**Issue by keedi** [opencloset/OpenCloset-Schema#36]
다음 이슈들과 연결된 이슈입니다.
- opencloset/monitor#65
- opencloset/opencloset#599

포장과  결제 사이 단계에서 버퍼 역할을 할 포장완료 상태가 필요하다고 합니다. 이유인즉 포장에서 결제로 넘길 때 병목이 이루어지지 않게 눈치를 보면서 한명씩 넘긴다고 합니다. 결제 상태로 바뀌면 사람들이 결제하는 장소에 몰리기 때문입니다. 이를 해결하기 위해 가운데 영역의 상태가 필요합니다.

**Comment by keedi** [comment]
기존 데이터베이스에는 다음 질의를 추가로 실행해야 합니다.

``` sql
INSERT INTO `status` (`name`) VALUES ('포장완료');
```

**Comment by keedi** [comment]
cpan.theopencloset.net 에 릴리스 완료했습니다.

**Comment by aanoaa** [comment]
죄송합니다.
코드상에 바뀐게 없어서 release 안해도 되는 줄 알았습니다.
