### ISSUE TITLE
상하의 한벌의 옷에 대한 데이터 저장

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#37]
https://github.com/opencloset/opencloset/issues/79 에서 파생되었습니다.

상하의 한벌의 옷에 대해
- 자켓 과 팬츠
- 자켓 과 스커트

기록해야 합니다.

이를 위해 스키마를 변경하고 재배포해야 합니다.

**Comment by yongbin** [comment]
이거 검색에도 영향이 있는 이슈입니다. 같이 이야기를 좀 해봐야할거 같습니다.

**Comment by aanoaa** [comment]
기존 테이블의 변경은 없고 추가되는건데도 영향이 있나요?

**Comment by aanoaa** [comment]
이건 시간이 좀 더 필요합니다.
#38, #39 와 함께 배포되기 어렵습니다.

**Comment by keedi** [comment]
기존 그룹 테이블로 해결하지 않고 결국 추가하셨군요. 흠...
추가해서 처리한도고 하더라도 현재 스키마 컬럼명을 고려하면 외래키는 테이블명, 컬럼명을 붙이고 있으니 clothes_code_top clothes_code_bottom 이 되야겠군요.

**Comment by keedi** [comment]
체인지 로그에는 이슈 번호가 있다면 추가해주세요.

**Comment by keedi** [comment]
> 체인지 로그에는 이슈 번호가 있다면 추가해주세요.

이후 pr에서 넣으셨네요. 확인했습니다.
