### ISSUE TITLE
주문서에 입고가는 사람에 대한 컬럼추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#38]
https://github.com/opencloset/opencloset/issues/648 를 해결하기 위한 이슈입니다.

`order` 테이블에 `is_wearing` 또는 `on_wearing` 컬럼을 추가해서 재배포 하여야 합니다.

**Comment by keedi** [comment]
컬럼 이름을 `does_wear`로 변경 요망드립니다.

**Comment by aanoaa** [comment]
수정하였습니다.

**Comment by keedi** [comment]
릴리스 진행해야 하는 줄 알고 PR 진행하고 있었습니다. 커멘트 남겨주시면 확인 후 진행하겠습니다.

**Comment by aanoaa** [comment]
스키마 변경에 관련된 이슈가 3개정도가 있습니다.
따로따로 릴리스할게 아니라 한번에 진행하시면 덜 번거롭겠네요.

**Comment by aanoaa** [comment]
@10001if 님 한테 기능에 대한 확인 받았습니다.
