### ISSUE TITLE
합격 여부를 저장할 수 있는 컴럼 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#39]
https://github.com/opencloset/opencloset/issues/655

@keedi `order` 혹은 `order_detail` 에 추가 컬럼이 필요합니다.
위 이슈에서 몇가지 후보를 올려놓았으니 보시고 점지해주세요.

**Comment by aanoaa** [comment]
`order` 보다는 `order_detail` 에 `pass` 컬럼을 추가하도록 하겠습니다.

**Comment by aanoaa** [comment]
주문서와 크게 상관이 없을 것 같아서 `order_detail` 에 넣으려 했는데,
order 와 order_detail 이 `1:N` 이네요.

주문서에 들어가는 것이 더 낫겠습니다.

**Comment by aanoaa** [comment]
@10001if 님 한테 기능에 대한 확인 받았습니다.

**Comment by keedi** [comment]
pass 라는 단어가 워낙 흔하다보니 코드 분석시 헷갈릴 여지가 있습니다.
pass -> employment 로 컬럼 이름 변경 요청드립니다.

**Comment by aanoaa** [comment]
@keedi 변수명 하나하나 신경쓰지마시고 저한테 맡겨주세요
pass 가 되었든 employment 가 되었든 상관없습니다.
