### ISSUE TITLE
주문서에 택배 운송장 번호를 저장할 수 있어야 함

### ISSUE THREAD

**Issue by keedi** [opencloset/OpenCloset-Schema#4]
opencloset/opencloset#330 이슈 중 데이터베이스 스키마 관련 내용은 이곳에서 처리되어야 합니다.

> @10001if wrote:
> 
> 방문대여나 온라인 대여 모두 택배 반납이 가능합니다.  현재는 택배 발송 기준으로 대여기간을 정하고 있습니다.  택배 도착여부는 개인이 관리할 수 없는 문제이기 대문입니다.
> 
> 때문에 개인이 택배 반납을 원할 경우 그에 대해 설명을 드리고 반납시 택배회사와 운송장번호를 SMS로 보내도록 하고 있습니다. SMS를 받아 따로 정리하는 것은 아니며, 형식적으로 운영하기 위한 방법 중 하나였습니다. (이렇게 하면 반납에 관한 강제성 내지는 압박감 등이 생길 수 있을 것이라는 느낌적인 느낌이 들었습니다..)
> 
> 하지만 앞으로는 조금 체계적으로 관리해야겠다는 생각이 들었습니다. 반납과 관련한 이슈가 계속 발생하고 있기 때문인데요. 그래서 택배 운송장번호가 SMS 오면 주문서에 그 내용을 입력할 수 있는 항목이 필요하다고 보여집니다. 가능하다면 삽입한 운송장번호를 클릭하면 현재 위치가 나오는 (배송사에서 제공한 페이지) 곳으로 이동하여 위치 정보를 확인 할 수 있다면 더 좋을 것 같습니다.

**Comment by aanoaa** [comment]
스키마 변경없이 운송장번호를 입력할 수 있도록 하였습니다.

https://github.com/opencloset/opencloset/pull/370

**Comment by keedi** [comment]
@aanoaa 엇 알겠습니다. 스키마 변경 없이 완료된 것이라면 이쪽 이슈는 닫겠습니다.
