### ISSUE TITLE
스커트둘레를 주문서와 사용자 정보에 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#46]
https://github.com/opencloset/opencloset/issues/602

에서 필요로 하기 때문에 해결되어야 합니다.

**Comment by yongbin** [comment]
제가 #27 처리하면서 같이 처리하겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Schema/tree/%2346-skirt-girth 이미 진행하고 있습니다.
이건 제가 할테니 할거 하십쇼

**Comment by yongbin** [comment]
앗 알겠습니다.
