### ISSUE TITLE
의류의 대여일, 보유일, 대여회전율을 제공하는 함수 추가

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Schema#48]
https://github.com/opencloset/opencloset/issues/714 을 처리하기 위해서 필요합니다.

**Comment by yongbin** [comment]
`Clothes` 객체는 
- rentable_duration()
- rented_duration()
- rent_ratio()

함수를 가지게 되었습니다.

**Comment by aanoaa** [comment]
``` perl
sub rent_ratio {
    my $self = shift;

    return $self->rented_duration() / $self->rentable_duration();
}
```

`rentable_duration()` 가 `0` 일때를 고려해야 합니다.

**Comment by aanoaa** [comment]
```
Use of uninitialized value in division (/) at /home/aanoaa/repo/opencloset/OpenCloset-Schema/lib/OpenCloset/Schema/Result/Clothes.pm line 483.
```

**Comment by keedi** [comment]
이제와서 뒤늦게 보는 거지만 타임존을 하드코딩했네요. 그러면서 `now()` 호출 때는 타임존 설정 안했고... 문제가 발생하지 않을 수도 있지만 문제의 소지가 있는 코드입니다.

**Comment by keedi** [comment]
2014년 12월 17일도 그렇고 이런식으로 모듈에 하드 코딩하는 건...;;; (주석도 없는데;;; )

**Comment by yongbin** [comment]
말씀하신 부분 #74 에 별도 이슈로 열었습니다. 확인해주셔서 감사합니다!
