### ISSUE TITLE
주문서에 반납메모컬럼을 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#50]
https://github.com/opencloset/opencloset/issues/611

반납후에 작성된 메모를 보여주기 위해 필요합니다.

**Comment by aanoaa** [comment]
네이밍의 시간입니다.

`return_memo` 어떨까요?

**Comment by yongbin** [comment]
현재
- `desc`  : 주문서 메모
- `message` : 대여 메세지

**Comment by aanoaa** [comment]
- `return_comment`
- `return_memo`
- `return_desc`
- `return_message`

최고 어려움
