### ISSUE TITLE
의류의 밑단둘레 cuff 를 소수점 2자리까지 입력

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#59]
https://github.com/opencloset/opencloset/issues/789

**Comment by aanoaa** [comment]
`clothes` 테이블 뿐만 아니라, `order_size_log` 테이블 및 trigger 에도 영향이 있습니다.

**Comment by aanoaa** [comment]
``` sql
ALTER TABLE `clothes` MODIFY `cuff` DECIMAL(3, 2) DEFAULT 0.00;
```

제 개발환경에서 위 구문을 실행하니까 기존에 있던 cuff 의 값이 `22`
에서 `9.99` 로 변경되었습니다.

현재 cuff 가 입력된 자료는 19개 행입니다.
기록해두고 업데이트 해주어야 합니다.

**Comment by aanoaa** [comment]
```
mysql> SELECT id, cuff FROM clothes WHERE cuff != 0;
+------+------+
| id   | cuff |
+------+------+
| 9470 |   15 |
| 9444 |   20 |
| 9446 |   20 |
| 9746 |   20 |
| 9676 |   21 |
| 9737 |   21 |
| 9418 |   22 |
| 9428 |   22 |
| 9442 |   22 |
| 9448 |   22 |
| 9462 |   22 |
| 9469 |   22 |
| 9683 |   22 |
| 9687 |   22 |
| 9464 |   23 |
| 9472 |   23 |
| 9452 |   24 |
| 9680 |   24 |
| 9689 |   24 |
+------+------+
```

**Comment by aanoaa** [comment]
`Wed, 20 Apr 2016 18:37:29 +0900` 으로 그렇다는거지 내일이면 더 늘어날 수 있습니다.

**Comment by aanoaa** [comment]
OpenCloset-Schema-0.028 를 배포하였습니다.

**Comment by aanoaa** [comment]
너무 성급하게 배포하였습니다.

> clothes 테이블 뿐만 아니라, order_size_log 테이블 및 trigger 에도 영향이 있습니다.

처리를 해야 합니다.

**Comment by yongbin** [comment]
진행합니다.

**Comment by yongbin** [comment]
확인결과 기존에 추가했던 `cuff`와 관련해서 두가지 문제점이 있습니다. 
1. 새로운 컬럼이 ADD 되면서 기존 모든 값이 default 값인 0이 들어감.
2. 우리가 의도한 999.99를 표현하기 위한 DECIMAL 자료형의 표현은 DECIMAL(3,2)이 아니라 DECIMAL(5,2)였음

현재 실DB 스키마 기준으로 이 두가지 문제를 해결하면서 trigger동작에도 이상이 없는 PR을 만들어서 보내겠습니다.

**Comment by aanoaa** [comment]
OpenCloset-Schema-0.029 를 배포하였습니다.

**Comment by aanoaa** [comment]
이거 생각해보니까 DB에 옇고 뺄때, inflate, deflate 자동으로 하게 할 수 있을 것 같습니다.
헬퍼 도움없이 그냥 inch 넣고 inch 로 빠지는데 알아서 cm 로 저장되는거죠.

**Comment by aanoaa** [comment]
e4b507d9cc2197a340d274ed08ecb0c7c1c2083e...2c02c4b3f920f267a6fbd1bf96fcc60d3c782c02
