### ISSUE TITLE
dbicdump 설정 파일이 OpenCloset::Util 모듈에 의존함

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Schema#6]
dbicdump에서 사용하는 db/schema-loader.pl 에 DSN등의 설정이 아직 기존에 사용하던 opencloset의 app.conf를 참고합니다.  저장소가 분리되었기 때문에 app.conf를 참조하는것은 적절하지 않습니다. 기존 설정을 참고해서 환경변수를 참조하도록 수정해야합니다.

**Comment by yongbin** [comment]
https://github.com/opencloset/OpenCloset-Schema/blob/develop/db/schema-loader.pl#L7

**Comment by yongbin** [comment]
opencloset 을 참조하는 부분을 환경변수를 수정하도록 수정하고 기존 기본설정을 옮겼습니다. 이슈닫습니다.

**Comment by keedi** [comment]
머지전에 코드 리뷰 했으면 하는 저장소니 다이렉트로 머지하거나 이슈 닫지 않았으면 합니다.

일단 머지 및 이슈 닫혔으니 그대로 둡니다.

**Comment by aanoaa** [comment]
이게 까먹을 수 있으니 README 같은곳에 적어두면 좋을 것 같습니다.

**Comment by keedi** [comment]
설정은 최대한 통합해서 사용하려고 합니다.

일단 이슈를 다시 열고 수정할 부분은 추가로 수정하겠습니다. #8 항목이 오래 밀려있는 상태이고 의존 이슈도 많은 관계로 우선 #8 을 처리한 후 마저 진행하겠습니다.

**Comment by keedi** [comment]
이번 `v0.004` 릴리스에 포함할 내역입니다. 오늘중으로 마무리 짓고 릴리스하는 것이 목표입니다. 진행합니다.

**Comment by keedi** [comment]
OpenCloset::Config 모듈의 0.001 버전을 열린옷장 cpan에 릴리스 했습니다. 관련 주소는 다음과 같습니다.
- 릴리스: https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Config-0.001.tar.gz
- 저장소: https://github.com/opencloset/OpenCloset-Config

**Comment by keedi** [comment]
OpenCloset::Config 모듈을 사용해서 `db/schema-loader.pl` 파일을 사용할 수 있도록 수정했습니다. 실행시 다음처럼 명령을 입력하면 됩니다.

``` bash
$ OPENCLOSET_CONFIG=../path/to/config dbicdump -Ilib db/schema-loader.pl
```

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다. :)

**Comment by keedi** [comment]
모듈 설치 방법은 다음과 같습니다.

``` bash
$ cpanm --mirror=https://cpan.theopencloset.net --with-develop OpenCloset::Schema
```

`OpenCloset::Config` 모듈은 개발할 때, 특히 `dbicdump`를 실행할 때만 필요하기 때문에 굳이 실행시점 의존성에 걸지 않고 개발 의존성에 걸었습니다. 따라서 설치시 `--with-develop` 옵션을 주어서 설치해야 합니다. :-)

**Comment by yongbin** [comment]
OpenCloset::Config 모듈을 설치했고 app.conf를 로드해서 `dbicdump`가 성공적으로 실행되는것을 확인했습니다. 수고하셨습니다.
