### ISSUE TITLE
의류 대여 가능일 계산이 정확하지 않음

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Schema#74]
@keedi 님이 확인해주신 이슈입니다. 
- https://github.com/opencloset/OpenCloset-Schema/issues/48#issuecomment-221472141
- https://github.com/opencloset/OpenCloset-Schema/issues/48#issuecomment-221472297

정리하면 잠재적으로 다음 사항들이 문제소지가 있습니다.
- 타임존 하드코딩
- 기준시점(2014년12월 17일) 하드코딩

https://github.com/opencloset/opencloset/issues/540 에서 논의되는 함수의 적절한 위치이슈와 별개로 우선 해결방법을 강구하겠습니다.

**Comment by aanoaa** [comment]
가능하다면 기존의 테스트코드를 참고해서 테스트파일도 추가해주세요.

**Comment by yongbin** [comment]
@aanoaa 넵 #81, #77 에서 기존 테스트 참고해서 추가해두었습니다.

**Comment by keedi** [comment]
@yongbin 이 작업이 완료되면 opencloset/opencloset 저장소에도 변경된 내용을 적용할 수 있는 PR을 보내셔야 합니다.

**Comment by yongbin** [comment]
https://github.com/opencloset/opencloset/pull/836 PR 보냈습니다.

**Comment by keedi** [comment]
완료되었으니 이슈 닫습니다.
