### ISSUE TITLE
의류 대여일 계산시 대여일보다 반납일이 이른경우 처리

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Schema#75]
https://github.com/opencloset/opencloset/issues/540#issuecomment-221488046

https://github.com/opencloset/opencloset/issues/832 같은이유로 대여일이 반납일보다 이른경우가 있습니다. 이런 경우에는 정상적이지 않은 주문서로 간주하고 대여일계산에서 제거하는게 적절합니다.

**Comment by yongbin** [comment]
rented_duration에서는 다음과 같이 처리했습니다. 

```perl
    foreach my $order_detail (@order_detail) {
        my $rental_date = $order_detail->order->rental_date->truncate( to => 'day' );
        my $return_date = $order_detail->order->return_date->truncate( to => 'day' );

        next unless $rental_date <= $return_date;

        my $delta = $return_date->subtract_datetime($rental_date)->in_units('days');

        $sum += $delta;
    }
```

```perl
sub rentable_duration {
    my $self = shift;

    my $start_dt =
        DateTime->new( year => 2014, month => 12, day => 17, time_zone => 'Asia/Seoul' );
    my $create_dt = $self->donation->create_date;
    my $entry_dt  = $create_dt < $start_dt ? $start_dt : $create_dt;
    my $now       = DateTime->now()->truncate( to => 'day' );

    # die unless $entry_dt <= $now
    # or
    # return 0 unless $entry_dt <= now

    return $now->truncate( to => 'day')->delta_days($entry_dt)->in_units('days');
}
```
@keedi , @aanoaa  `rentable_duration` 의 경우 0으로 리턴하는게 맞을까요? 죽는게 맞을까요? 혹은 다른방식으로 처리해야할까요?

**Comment by keedi** [comment]
코드 리뷰하면서 `DateTime` 모듈의 `delta_days()` 메소드에 대해 더 정확히 알게 되었습니다. 확인한 내용은 다음과 같습니다.
- 항상 양수값(절대값)을 반환한다.
- 객체의 로컬(시간대를 적용한) 날짜를 기준으로 계산하며 계산 시 시간대 정보를 무시한다.
- 날짜 기준으로 날짜 이하 부분은 절삭해서 계산한다.

**Comment by keedi** [comment]
더불어 기존에는 대여일과 반납일이 같은 경우 계산하지 않았는데 이를 처리해서 1일로 계산하도록 했으며 기존 연산 값에 1을 더해서 1박 2일인 경우 의류 대여일은 1이 아닌 2로 계산하도록 수정했습니다.

**Comment by keedi** [comment]
또한 의류 대여일 계산 메소드 호출 시 시간대 정보를 입력 받아(옵션) 해당 시간대 기준으로 의류 대여일을 계산할 수 있도록 했습니다.

**Comment by keedi** [comment]
작업 완료했으므로 이슈 닫습니다.

@yongbin 고생하셨습니다.
