### ISSUE TITLE
주문서의 상태변화 시점과 상태별 경과시간 지원

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Schema#8]
https://github.com/opencloset/opencloset/issues/318 을 처리하기 위해서 주문서의 상태변화 시점과 상태별 경과시간을 알수 있는 통일된 방법이 있으면 좋겠습니다.

**Comment by keedi** [comment]
확인중입니다.

**Comment by keedi** [comment]
PR을 `develop`에 머지 완료했습니다. 추가로 처리한 내역은 다음과 같습니다.
- 문서 정리
- 코드 리팩터링
- 메소드를 하나로 통합: `analyze_order_status_log()`
- 체인지로그 갱신

**Comment by keedi** [comment]
이슈 닫고 릴리스 준비하겠습니다.

@yongbin: 고생하셨습니다.

**Comment by yongbin** [comment]
@keedi 네 오히려 더 수고 많으셨습니다. 수정해주신 최종 코드나 내용 모두다 확인했습니다. 함수를 합치고 경과시간을 초로 처리한 부분이 속도적인 측면에서도 이득이 많아보입니다. 이번에 손봐주신 내용이나 작업들 참고해서 다음에는 좀 더 꼼꼼하게 PR 보내도록 하겠습니다. 감사합니다.
