### ISSUE TITLE
주문서.운송장번호 컬럼 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Schema#91]
여러개의 컬럼이 필요합니다.
따로 테이블을 만드는 것이 좋을지, 아니면 주문서 테이블에 컬럼을 추가하는 것이 좋을 지
모르겠습니다.
- 택배사
- 운송장번호
- 반송장번호
- sms_bitmask
- comment
- 택배보낸날짜
- 택배받은날짜
- 반송보낸날짜
- 반송받은날짜

`sms_bitmask` 가 뭐냐면, 상태변경마다 sms 를 하나씩 보내고 그걸 보냈는지 안보냈는지
체크하는 컬럼

**Comment by aanoaa** [comment]
`order` 테이블에 컬럼을 추가하는 방식이 아니라,
`order_parcel` 테이블을 새로 만들겠습니다.

오프라인 주문서에서는 사용되지 않는 컬럼들이라서 `order` 에 넣는 것은 적절해 보이지 않습니다.

**Comment by yongbin** [comment]
넵 저도 새로운 테이블에 추가하는게 좋아보입니다.

**Comment by aanoaa** [comment]
`order_parcel`
- id
- order_id
- service(택배사)
- waybill
- return_waybill
- sms_bitmask
- comment
- create_date
- update_date
- sent_date
- arrival_date
- return_sent_date
- return_arrival_date

**Comment by aanoaa** [comment]
order_parcel 테이블을 추가하였습니다.
기존 서비스에는 영향이 없습니다.
