### ISSUE TITLE
온라인 주문 지원

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Schema#94]
#27 과 별도로 OpenCloset::Schema를 사용하는 application 에서 좀 더 편하고 일관된 방법으로 주문을 처리할수 있는 기능을 제공합니다. https://github.com/opencloset/opencloset/issues/715 와 관련있습니다.

**Comment by aanoaa** [comment]
기존의 주문서에서 온라인 주문서를 찾아서 새로 추가된 column 의 값을 변경해주면 되지
않을까요? 그리고 그 컬럼을 기준으로 온/오프 를 구별하도록 프로그램을 바꾸고요.

**Comment by yongbin** [comment]
네 #27 과 별도로 진행되는거라서 새로 컬럼이 추가되면 그쪽으로 기존 값은 이전할예정입니다. 이 PR에서 추가된 인터페이스로 application을 변경하는게 온/오프를 구별하는 부분들을 찾는 과정이니까 결과적으로는 최후에는 ResultSet subclass 가 구현이 아주 간소해 지거나 혹은 다시 지워질수도 있을거 같습니다. 다만 온/오프라인 구분은 지금까지도 아주 많았고 앞으로도 계속 반복적으로 사용될 패턴이라서 이번기회에 이런식으로 인터페이스를 합치는것도 괜찮다고 생각합니다.

결정해주시면 중단하던지 진행하던지 하겠습니다

**Comment by aanoaa** [comment]
온/오프 구분이 주문서의 `online` 컬럼 가지고 부족한가요?
기존의 온라인 주문서들의 `online` 을 `1` 로 바꾸면 될 것 같은데 다른 생각이 있으신 건가요?

**Comment by yongbin** [comment]
온오프라인 주문서 구분은 `online` 컬럼으로 충분합니다. 근데 저는 형석님이 https://github.com/opencloset/OpenCloset-Schema/issues/27#issuecomment-245860565 이렇게 의견주셔서 좀 더 방어적으로 진행했던겁니다. 뭔가 소통에 문제가 있었던거 같은데 필요성이 별로 없다고 생각하시면 PR 삭제해도 관계없습니다. 그럼 추가된 컬럼에 자료 옮기는것만 진행하면 될까요?

**Comment by aanoaa** [comment]
무엇을 하려는지 모르겠어서 남겼습니다.
코멘트를 보니 불필요해 보이는군요.

**Comment by yongbin** [comment]
넵 그럼 짬시키겠습니다.
